### ISSUE TITLE
Unable to build brach release-5.5.0 - Eclipse

### ISSUE THREAD

**Issue by cryptton2004** [SmartBear/soapui#471]
Hello,

Following this tutorial:

> 
> Eclipse
> 
> Open project
> 
>     Clone the project
>     In the main menu, select File > Import.
>     In the Import dialog, select Maven > Existing Maven projects and click Next.
>     In the Root directory, enter the path to the root folder of the SoapUI project and click Finish.
> 
> Run SoapUI
> 
> After you have created the Eclipse project, navigate to the com.eviware.soapui.SoapUI class, right-click it and select Run as > Java application.
> 
> Get the latest changes
> 
>     Right-click on the root folder in the Package explorer panel.
>     Select Team > Pull.

I just have to fix error, after error. There's no way you can build this as described. Has anyone tested it? Can anyone confirm that on a fresh environment, you can follow the above instructions? I just want to rule out that the problem is on my machine. Two people have tested this on two different machines with different java versions, and we're getting different results (by results I mean errors).

Before I go further and provide error stacks or try to spend more time building it (already lost an entire day), can someone confirm that this release (5.5.0) or any release can be built with the steps described above for Eclipse? 

This is the latest:
`Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.eviware.soapui.config.SoapuiSettingsDocumentConfig$Factory.parse(SoapuiSettingsDocumentConfig.java:59)
	at com.eviware.soapui.DefaultSoapUICore.initSettings(DefaultSoapUICore.java:259)
	at com.eviware.soapui.DefaultSoapUICore.init(DefaultSoapUICore.java:141)
	at com.eviware.soapui.DefaultSoapUICore.<init>(DefaultSoapUICore.java:126)
	at com.eviware.soapui.DefaultSoapUICore.createDefault(DefaultSoapUICore.java:105)
	at com.eviware.soapui.SoapUI.getSettings(SoapUI.java:1699)
	at com.eviware.soapui.SoapUI$SoapUIRunner.run(SoapUI.java:792)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Cannot load SchemaTypeSystem. Unable to load class with name schemaorg_apache_xmlbeans.system.s05EC9A3AACC8687CD214E9B1A496DB91.TypeSystemHolder. Make sure the generated binary files are on the classpath.
	at org.apache.xmlbeans.XmlBeans.typeSystemForClassLoader(XmlBeans.java:783)
	at com.eviware.soapui.config.SoapuiSettingsDocumentConfig.<clinit>(SoapuiSettingsDocumentConfig.java:20)
	... 21 more
Caused by: java.lang.ClassNotFoundException: schemaorg_apache_xmlbeans.system.s05EC9A3AACC8687CD214E9B1A496DB91.TypeSystemHolder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.xmlbeans.XmlBeans.typeSystemForClassLoader(XmlBeans.java:769)
	... 22 more`

**Comment by cryptton2004** [comment]
I eventually made it work. Didn't track all the changes that I made, but I think there were some conflicts between my IDE settings and the project settings. Also, having multiple jdk environments made things a little harder.
