### ISSUE TITLE
SoapUI 5.5.0 crashes on startup when MacOS system proxy enabled

### ISSUE THREAD

**Issue by jaroslawhartman** [SmartBear/soapui#473]
Hi,

When a system proxy for any connection is enabled, SoapUI cashes on the splash screen upon startup:

```
+ /usr/bin/java -Xms128m -Xmx1024m -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -Dsoapui.properties=soapui.properties -Dgroovy.source.encoding=iso-8859-1 -Dsoapui.home=/Applications/SoapUI-5.5.0.app/Contents/java/app/bin -splash:SoapUI-Spashscreen.png -Dswing.crossplatformlaf=apple.laf.AquaLookAndFeel -Dapple.eawt.quitStrategy=CLOSE_ALL_WINDOWS -Dsoapui.ext.libraries=/Applications/SoapUI-5.5.0.app/Contents/java/app/bin/ext -Dsoapui.ext.listeners=/Applications/SoapUI-5.5.0.app/Contents/java/app/bin/listeners -Dsoapui.ext.actions=/Applications/SoapUI-5.5.0.app/Contents/java/app/bin/actions -Djava.library.path=/Applications/SoapUI-5.5.0.app/Contents/java/app/bin -Dwsi.dir=/Applications/SoapUI-5.5.0.app/Contents/java/app/wsi-test-tools -Dsoapui.browser.disabled=true -cp '/Applications/SoapUI-5.5.0.app/Contents/PlugIns/jre.bundle/Contents/Home/jre/lib/jfxrt.jar:/Applications/SoapUI-5.5.0.app/Contents/java/app/bin/soapui-5.5.0.jar:/Applications/SoapUI-5.5.0.app/Contents/java/app/lib/*' com.eviware.soapui.SoapUI
Configuring log4j from [/Applications/SoapUI-5.5.0.app/Contents/java/app/bin/soapui-log4j.xml]
14:05:11,857 INFO  [DefaultSoapUICore] Creating new settings at [/Users/jhartman/soapui-settings.xml]
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.eviware.soapui.impl.wsdl.support.http.HttpClientSupport.<clinit>(HttpClientSupport.java:73)
	at com.eviware.soapui.DefaultSoapUICore.initSettings(DefaultSoapUICore.java:373)
	at com.eviware.soapui.DefaultSoapUICore.init(DefaultSoapUICore.java:141)
	at com.eviware.soapui.DefaultSoapUICore.<init>(DefaultSoapUICore.java:126)
	at com.eviware.soapui.DefaultSoapUICore.createDefault(DefaultSoapUICore.java:105)
	at com.eviware.soapui.SoapUI.getSettings(SoapUI.java:1699)
	at com.eviware.soapui.SoapUI$SoapUIRunner.run(SoapUI.java:792)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: ProxySelector must not be null.
	at com.btr.proxy.selector.whitelist.ProxyBypassListSelector.<init>(ProxyBypassListSelector.java:39)
	at com.btr.proxy.selector.whitelist.ProxyBypassListSelector.<init>(ProxyBypassListSelector.java:54)
	at com.btr.proxy.search.desktop.osx.OsxProxySearchStrategy.installExceptionList(OsxProxySearchStrategy.java:224)
	at com.btr.proxy.search.desktop.osx.OsxProxySearchStrategy.buildSelector(OsxProxySearchStrategy.java:141)
	at com.btr.proxy.search.desktop.osx.OsxProxySearchStrategy.getProxySelector(OsxProxySearchStrategy.java:113)
	at com.btr.proxy.search.desktop.DesktopProxySearchStrategy.getProxySelector(DesktopProxySearchStrategy.java:34)
	at com.btr.proxy.search.ProxySearch.getProxySelector(ProxySearch.java:193)
	at com.eviware.soapui.impl.wsdl.support.http.ProxyUtils.setGlobalProxy(ProxyUtils.java:187)
	at com.eviware.soapui.model.propertyexpansion.PropertyExpander.<clinit>(PropertyExpander.java:80)
	... 21 more
```

Workaround:
* Turn off all proxies in Network configuration, see e.g. [this link](https://www.linksys.com/us/support-article?articleNum=135932)
* Start SoapUI and disable proxy

![image](https://user-images.githubusercontent.com/964833/61631584-0a9cf180-ac8b-11e9-94cf-7b7d81dfca85.png)

* Quit SoapUI
* Re-enable MacOS system proxies

Best regards,
Jarek

**Comment by uurlasrl** [comment]
there is an issue also in 5.7.0 solved by edit directly ~/soapui-settings.xml 
set to fase the following two properties
    <con:setting id="ProxySettings@autoProxy">false</con:setting>
    <con:setting id="ProxySettings@enableProxy">false</con:setting>
