### ISSUE TITLE
SoapUI OpenSource Linux 64bit require java 9

### ISSUE THREAD

**Issue by rinkesj** [SmartBear/soapui#530]
Hi,

I use Linux 64bit installer for SoapUI 5.6.0 and on startup SOAPUI is not able run with Java 8.

java.lang.UnsupportedClassVersionError: com/eviware/soapui/SoapUI has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:62)

```
❯ java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

SOAPUI download page also missing versions between latest and 5.2.1.
https://www.soapui.org/downloads/soapui/soapui-os-older-versions/

**Comment by chinnaxs** [comment]
Exactly the same problem here

**Comment by ReadyAPIAgent** [comment]
5.6.0 is build against java12. It doesn't support Java8

**Comment by ReadyAPIAgent** [comment]
about missed releases please updated 5.6.1 within required version in the link below 
https://dl.eviware.com/soapuios/5.6.1/SoapUI-x64-5.6.1.exe

to get the required version. Sorry for missing release in GitHub
