### ISSUE TITLE
Community version does not start

### ISSUE THREAD

**Issue by guai** [SmartBear/soapui#636]
```
java.lang.UnsupportedClassVersionError: com/eviware/soapui/SoapUI has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
```
I have several JDKs on this pc, default is 11.
As I can see SoapUI ships its own jre. I guess something went wrong and it tries to start with the default jdk

**Comment by guai** [comment]
the version is 5.5.6

**Comment by guai** [comment]
5.5.0 starts ok

**Comment by ReadyAPIAgent** [comment]
have you checked against newest version? to be sure the product operates correctly SoapUI prefers its own JRE. We can not gurantee compatibility with other JREs/JDKs.

**Comment by ReadyAPIAgent** [comment]
Please check against 5.7.0 and reopen the issue if is still actual
