### ISSUE TITLE
macOS SoapUI 5.7.0 fails to start: “libprism_es2.dylib” will damage your computer.

### ISSUE THREAD

**Issue by hussam-qasem** [SmartBear/soapui#772]
SoapUI 5.7.0 failed to start this morning, with an error message:

`“libprism_es2.dylib” will damage your computer. You should move it to the Trash.`
<img width="453" alt="Screen Shot 2023-07-25 at 9 34 45 AM" src="https://github.com/SmartBear/soapui/assets/68053227/be69700b-3395-4521-b65d-5d993a6f17b1">

and:

`“libprism_sw.dylib” will damage your computer. You should move it to the Trash.`
<img width="453" alt="Screen Shot 2023-07-25 at 9 34 57 AM" src="https://github.com/SmartBear/soapui/assets/68053227/26842d74-5412-4535-b36b-6f30ac7cbd1f">

When running from the command-line, I get the following:
`WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @67a9629b'`
<details>
  <summary>/Applications/SoapUI-5.7.0.app/Contents/java/app/bin/soapui.sh</summary>

```java
================================
=
= SOAPUI_HOME = /Applications/SoapUI-5.7.0.app/Contents/java/app
=
================================
Configuring log4j from [/Applications/SoapUI-5.7.0.app/Contents/java/app/bin/soapui-log4j.xml]
09:32:38,486 INFO  [DefaultSoapUICore] initialized soapui-settings from [/Users/user/soapui-settings.xml]
09:32:39,371 INFO  [PluginManager] Adding plugin from [/Users/user/.soapuios/plugins/ready-mqtt-plugin-dist.jar]
09:32:39,371 INFO  [PluginManager] Adding plugin from [/Users/user/.soapuios/plugins/readyapi-postman-1.0.1.jar]
09:32:40,091 INFO  [PluginManager] Adding plugin from [/Users/user/.soapuios/plugins/ready-uxm-plugin-1.0.1-dist.jar]
09:32:40,533 WARN  [PluginManager] Could not load plugin from file [/Users/user/.soapuios/plugins/ready-uxm-plugin-1.0.1-dist.jar]
com.eviware.soapui.plugins.InvalidPluginException: Error loading plugin class com.smartbear.ready.PluginConfig
	at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:115) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:55) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManager.java:157) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginManager.access$700(PluginManager.java:43) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSequentially(PluginManager.java:436) [soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(PluginManager.java:393) [soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(PluginManager.java:398) [soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(PluginManager.java:381) [soapui-5.7.0.jar:5.7.0]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/eviware/soapui/ui/NavigatorListener
	at com.smartbear.ready.MonitorApisAction.<init>(MonitorApisAction.java:25) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at com.eviware.soapui.plugins.LoaderBase.createObject(LoaderBase.java:90) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.LoaderBase.createAction(LoaderBase.java:308) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.LoaderBase.loadActions(LoaderBase.java:290) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginLoader.loadPluginActions(PluginLoader.java:168) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:106) ~[soapui-5.7.0.jar:5.7.0]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.eviware.soapui.ui.NavigatorListener
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.eviware.soapui.plugins.JarClassLoader.loadClass(JarClassLoader.java:65) ~[soapui-5.7.0.jar:5.7.0]
	at com.smartbear.ready.MonitorApisAction.<init>(MonitorApisAction.java:25) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at com.eviware.soapui.plugins.LoaderBase.createObject(LoaderBase.java:90) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.LoaderBase.createAction(LoaderBase.java:308) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.LoaderBase.loadActions(LoaderBase.java:290) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginLoader.loadPluginActions(PluginLoader.java:168) ~[soapui-5.7.0.jar:5.7.0]
	at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:106) ~[soapui-5.7.0.jar:5.7.0]
	... 13 more
09:32:40,545 INFO  [PluginManager] 3 plugins loaded in 1172 ms
09:32:40,545 INFO  [DefaultSoapUICore] All plugins loaded
09:32:40,878 INFO  [WorkspaceImpl] Loading workspace from [/Users/user/default-soapui-workspace.xml]
09:32:41,155 INFO  [WsdlProject] Loaded project from [file:/Users/user/Documents/SoapUI/whatever-soapui-project.xml]
09:32:42,731 INFO  [DefaultSoapUICore] Defaulting to native L&F for Mac OS X
09:32:43,392 INFO  [SoapUI] Used java version: 11.0.16.1
Jul 25, 2023 9:32:44 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @67a9629b'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/user/.openjfx/cache/16/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/user/.openjfx/cache/16/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:69)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/user/.openjfx/cache/16/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/user/.openjfx/cache/16/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by Alikhan247** [comment]
Same issue on MacOS Ventura

**Comment by gokulgovind** [comment]
@hussam-qasem  / @Alikhan247 Works fine with following step, (Atleast for me)

1. Download lower version,
https://dl.eviware.com/soapuios/5.6.1/SoapUI-5.6.1.dmg
2. From Appfile -> Right Click -> Get Info -> Enable [Override Malware Protection]
3. Restart the MAC
![Screenshot 2023-07-25 at 5 26 24 PM](https://github.com/SmartBear/soapui/assets/18026746/61357ffa-e2f4-4f7a-8ff2-22259b1d2a96)

**Comment by hussam-qasem** [comment]
>     1. Download lower version,
>        https://dl.eviware.com/soapuios/5.6.1/SoapUI-5.6.1.dmg
What's special about the older version?
>     2. From Appfile -> Right Click -> Get Info -> Enable [Override Malware Protection]
Unfortunately, I don't have that option! macOS Monterey 12.6.7
<img width="377" alt="Screen Shot 2023-07-25 at 3 04 40 PM" src="https://github.com/SmartBear/soapui/assets/68053227/f5c4b9c6-a89f-436b-a3da-12eb59c70007">

**Comment by gokulgovind** [comment]
> nately, I don't have that option! macOS Monterey 12

Not from DMG, 

Double tap on DMG, APP icon will be shown -> Get Info from here should have **Override Malware Protection** option. PFA

![Screenshot 2023-07-25 at 7 28 07 PM](https://github.com/SmartBear/soapui/assets/18026746/99c7b92b-6027-47e8-ae15-0924e815ae6d)

**Comment by hussam-qasem** [comment]
Confirmed to work. Thank you @gokulgovind
